apiVersion: cache.cloud.io/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached-sample
    app.kubernetes.io/part-of: memcached-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: memcached-operator
  name: memcached-sample
spec:
  # of Pods/Instances your Operand must have on cluster
  size: 2
  labels:
    environment: production

  containerPort: 11211

  resources: {}
  env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
#  image: memcached:1.6.29-alpine3.20
  image: bitnami/memcached:1.6.23-debian-11-r21
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  livenessProbe:
    tcpSocket:
      port: memcached
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  readinessProbe:
    tcpSocket:
      port: memcached
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 6
    successThreshold: 1



  metricsEnabled: true
  metricsImage: "bitnami/memcached-exporter:0.14.2-debian-11-r23"
  metricsResources: {}

  metricsLivenessProbe:
    httpGet:
      path: /metrics
      port: 9150
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  metricsReadinessProbe:
    httpGet:
      path: /metrics
      port: 9150
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1